name: FrontEnd deployment
on:
  push:
    branches:
      - main
jobs:
  build-deploy-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1

      - run: npm install
      - run: npm run build
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2 #https://github.com/marketplace/actions/install-ssh-key
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa 
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }} 
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
