const appModules = [
  {
    name: "Accounting",
    types: [""],
  },
  {
    name: "Admin",
    types: [""],
  },
  {
    name: "Blood Bank",
    types: [""],
  },
  {
    name: "Client",
    types: [""],
  },
  {
    name: "Clinic",
    types: [""],
  },
  {
    name: "Communication",
    types: [""],
  },
  {
    name: "Complaints",
    types: [""],
  },
  {
    name: "CRM",
    types: [""],
  },
  {
    name: "Engagement",
    types: [""],
  },
  {
    name: "Epidemiology",
    types: [""],
  },
  {
    name: "Finance",
    types: [""],
  },
  {
    name: "Immunization",
    types: [""],
  },
  {
    name: "Inventory",
    types: [""],
  },
  {
    name: "Laboratory",
    types: [""],
  },
  {
    name: "Managed Care",
    types: [""],
  },
  {
    name: "Market Place",
    types: [""],
  },
  {
    name: "Patient Portal",
    types: [""],
  },
  {
    name: "Pharmacy",
    types: [""],
  },
  {
    name: "Radiology",
    types: [""],
  },
  {
    name: "Referral",
    types: [""],
  },
  {
    name: "Theatre",
    types: [""],
  },
  {
    name: "Ward",
    types: [""],
  },
  // {
  //   name: "",
  //   types: [""],
  // },
  // {
  //   name: "",
  //   types: [""],
  // },
  // {
  //   name: "",
  //   types: [""],
  // },
  // {
  //   name: "",
  //   types: [""],
  // },
];

const orgTypeModules = [
  {
    name: "Hospital",
    alias: [],
    modules: [
      "Admin",
      "Client",
      "Clinic",
      "Appointment",
      "Check-In",
      "Ward",
      "Laboratory",
      "Radiology",
      "Pharmacy",
      "Theatre",
      "Blood Bank",
      "Inventory",
      "Communication",
      "Immunization",
      "Finance",
      "Accounting",
      "Complaints",
      "Referral",
      "Epidemiology",
      "Engagement",
    ],
  },

  {
    name: "Pharmacy",
    alias: [],
    modules: [
      "Admin",
      "Client",
      "Clinic",
      "Appointment",
      "Check-In",
      "Ward",
      "Laboratory",
      "Radiology",
      "Pharmacy",
      "Theatre",
      "Blood Bank",
      "Inventory",
      "Communication",
      "Immunization",
      "Finance",
      "Accounting",
      "Complaints",
      "Referral",
      "Epidemiology",
      "Engagement",
    ],
  },

  {
    name: "Diagnostic Lab",
    alias: [],
    modules: [
      "Admin",
      "Client",
      "Clinic",
      "Appointment",
      "Check-In",
      "Ward",
      "Laboratory",
      "Radiology",
      "Pharmacy",
      "Theatre",
      "Blood Bank",
      "Inventory",
      "Communication",
      "Immunization",
      "Finance",
      "Accounting",
      "Complaints",
      "Referral",
      "Epidemiology",
      "Engagement",
    ],
  },
  {
    name: "HMO",
    alias: [],
    modules: [
      "Admin",
      "Client",
      "Clinic",
      "Appointment",
      "Check-In",
      "Ward",
      "Laboratory",
      "Radiology",
      "Pharmacy",
      "Theatre",
      "Blood Bank",
      "Inventory",
      "Communication",
      "Immunization",
      "Finance",
      "Accounting",
      "Complaints",
      "Referral",
      "Epidemiology",
      "Engagement",
    ],
  },
];
